name: gsheet_to_arb
version: 1.0.2
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  args: ">=2.0.0 <3.0.0"
  dart_style: ">=2.0.1 <3.6.0"
  intl: ">=0.19.0 <0.20.0"
  intl_generator:
    git:
      url: https://github.com/anycode/intl_generator.git
  path: ">=1.8.0 <2.0.0"
  googleapis_auth: ^1.1.0
  googleapis: ^13.2.0
  code_builder: ">=4.0.0 <5.0.0"
  json_annotation: any
  file_utils: ">=1.0.0 <1.1.0"
  logging: "^1.0.1"
  recase: "^4.0.0"
  quiver: "^3.0.1"
  yaml: ">=3.1.0 <3.2.0"
  petitparser: ">=5.0.0 <7.0.0" 

dev_dependencies:
  analyzer: any
  test: any
  build_runner: any
  json_serializable: any
  pedantic: any
